version: '3'

tasks:
  default:
    cmds:
      - task --list
    silent: true
  cluster:create:
    cmds:
      - kind create cluster --config=./infra/kind-config.yaml --name my-lab
    silent: true
    desc: "Create a Kubernetes cluster using Kind"
  cluster:delete:
    cmds:
      - kind delete cluster --name my-lab
    silent: true
    desc: "Delete the Kubernetes cluster created by Kind"

  cilium:install:
      desc: "Install Cilium with L7, Gateway API sand Kube-Proxy Replacement"
      cmds:
        - kubectl apply -f https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.1.0/standard-install.yaml
        - >
          cilium install 
          --set k8sServiceHost=my-lab-control-plane 
          --set k8sServicePort=6443 
          --set kubeProxyReplacement=true 
          --set gatewayAPI.enabled=true 
          --set hostServices.enabled=true 
          --set externalIPs.enabled=true
          --set l2announcements.enabled=true
          --set devices=eth0 
        - cilium status --wait
        - kubectl apply -f infra/l2policy.yaml
        - kubectl apply -f infra/pool.yaml

  python-env:
    cmds:
      - cd ./server && python3 -m venv venv
      - cd ./server && . venv/bin/activate && pip install -r requirements.txt && python3 setup_kc.py

  deploy-redis:
    desc: "Deploy Redis using CloudPirates OCI Chart"
    cmds:
      - helm repo add bitnami https://charts.bitnami.com/bitnami
      - helm repo update
      - helm upgrade --install my-redis bitnami/redis -f infra/redis-values.yaml
  keycloak:deploy:
    cmds:
      - helm upgrade --install keycloak oci://registry-1.docker.io/cloudpirates/keycloak -f infra/keycloak-values.yaml
      - kubectl get pods -w
  keycloak:port-forward:
    silent: true
    cmds:
     - echo port forwarding 8080
     - kubectl port-forward svc/keycloak 8080:8080 --address 0.0.0.0 
  keycloak:uninstall:
    cmds:
      - helm uninstall keycloak
  oauth2-proxy:deploy:
    desc: "Deploy OAuth2-Proxy using Helm"
    cmds:
      - helm repo add oauth2-proxy https://oauth2-proxy.github.io/manifests
      - helm repo update
      - helm upgrade --install oauth2-proxy oauth2-proxy/oauth2-proxy -f infra/oauth2-proxy-values.yaml

  deploy-all:
    desc: "Apply all Kubernetes manifests"
    cmds:
      - kubectl apply -f server/django-secret.yaml
      - kubectl apply -f infra/k8s/django-configmap.yaml
      - kubectl apply -f infra/k8s/django-deployment.yaml
      - kubectl apply -f infra/k8s/django-service.yaml
      - kubectl apply -f infra/k8s/gateway.yaml
      - kubectl apply -f infra/k8s/envoy-gateway.yaml
      - kubectl apply -f infra/k8s/route-keycloak.yaml
      - kubectl apply -f infra/k8s/route-django.yaml

  django:build:
    desc: "Build and load Django image into Kind"
    cmds:
      - docker build -t django-app:latest ./server
      - kind load docker-image django-app:latest --name my-lab
